SOURCEC		= fast_output.cxx
SOURCEH		= $(SOURCEC:%.cxx=%.hxx)
MODULE_DIR      = ../
SUB_NAME	= BoutFastOutput
TARGET		= sub

BOUT_TOP = /home/niflheim/$(USER)/north-simulation/shared/BOUT-dev
include $(BOUT_TOP)/make.config
